"""Internal auth resources (example 03).

The auth feature ships hand-written ORM models on ``AuthBase``
(:mod:`resourcey.auth.auth_models`) for its backing tables — IdP tokens, OAuth
clients, and API keys. This module declares those same entities as
``SqlResource`` subclasses so they are first-class resources: their
tables land in ``ResourceyBase.metadata`` and drive migration autogeneration
alongside ``Thread`` / ``Message`` / ``User`` / ``UserPermission``.

They are **not exposed externally**. Each overrides :meth:`get_exposed_resource`
to return ``None``, so :func:`~resourcey.resource.routes.register_routes`
registers no endpoints and they never appear in the OpenAPI surface. The auth
service continues to read/write these tables through the ``AuthBase`` ORM
models directly; the resource declarations exist so that *every* entity is part
of the single resource-derived schema, letting the migration be autogenerated
from ``ResourceyBase.metadata`` alone (no manual ``AuthBase`` merge).

Columns mirror :mod:`resourcey.auth.auth_models` field-for-field — type,
length, uniqueness, index, and foreign-key ``ondelete`` — so the autogenerated
migration reproduces the auth schema. The ``id`` columns use a Python-side
``uuid4`` default (SQLite has no ``gen_random_uuid()`` server default), matching
the other resources in this example.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated
from uuid import UUID, uuid4

from pydantic import Field
from resourcey.resource.base import BaseResource
from resourcey.resource.field import ResourceyField
from resourcey.resource.sql import SqlResource
from sqlalchemy import Column, ForeignKey, String, Uuid


class _InternalAuthResource(SqlResource):
    """Base for auth backing resources: secured but never REST-exposed.

    The auth service owns these tables via the ``AuthBase`` ORM models; they
    are declared as resources only so their schema is generated from the same
    ``ResourceyBase.metadata`` as everything else. ``get_exposed_resource``
    returns ``None`` so the route builder skips them entirely — no endpoints,
    no OpenAPI entries — while ``on_register`` still materialises their tables.
    """

    def get_exposed_resource(self) -> BaseResource | None:
        return None


class IdpRefreshToken(_InternalAuthResource):
    """An encrypted IdP refresh token persisted for a local user."""

    id: Annotated[
        UUID,
        ResourceyField(column=Column("id", Uuid, primary_key=True, default=uuid4, nullable=False)),
    ]
    creator_id: Annotated[
        UUID,
        ResourceyField(
            column=Column(
                "creator_id",
                Uuid,
                ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            )
        ),
    ]
    refresh_token: Annotated[
        str, ResourceyField(column=Column("refresh_token", String(8192), nullable=False))
    ]
    expires_at: datetime
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


_IdpRefreshTokenModel = IdpRefreshToken.get_sql_alchemy_model()


class IdpAccessToken(_InternalAuthResource):
    """An encrypted IdP access token persisted for a local user.

    References its backing :class:`IdpRefreshToken` (1:1, cascade delete).
    """

    id: Annotated[
        UUID,
        ResourceyField(column=Column("id", Uuid, primary_key=True, default=uuid4, nullable=False)),
    ]
    refresh_token_id: Annotated[
        UUID,
        ResourceyField(
            column=Column(
                "refresh_token_id",
                Uuid,
                ForeignKey("idp_refresh_tokens.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            )
        ),
    ]
    access_token: Annotated[
        str, ResourceyField(column=Column("access_token", String(8192), nullable=False))
    ]
    expires_at: datetime
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


_IdpAccessTokenModel = IdpAccessToken.get_sql_alchemy_model()


class OAuthClient(_InternalAuthResource):
    """A client registered to use this project as an OAuth provider."""

    id: Annotated[
        UUID,
        ResourceyField(column=Column("id", Uuid, primary_key=True, default=uuid4, nullable=False)),
    ]
    client_id: Annotated[
        str,
        ResourceyField(
            column=Column("client_id", String(128), nullable=False, unique=True, index=True)
        ),
    ]
    client_secret: Annotated[
        str, ResourceyField(column=Column("client_secret", String(8192), nullable=False))
    ]
    name: Annotated[
        str | None, ResourceyField(column=Column("name", String(255), nullable=True))
    ] = None
    enabled: bool = True
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


_OAuthClientModel = OAuthClient.get_sql_alchemy_model()


class OAuthClientRedirectUri(_InternalAuthResource):
    """A permitted redirect URI for an OAuth client (wildcard segments allowed)."""

    id: Annotated[
        UUID,
        ResourceyField(column=Column("id", Uuid, primary_key=True, default=uuid4, nullable=False)),
    ]
    client_id: Annotated[
        UUID,
        ResourceyField(
            column=Column(
                "client_id",
                Uuid,
                ForeignKey("oauth_clients.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            )
        ),
    ]
    uri: Annotated[str, ResourceyField(column=Column("uri", String(2048), nullable=False))]
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


_OAuthClientRedirectUriModel = OAuthClientRedirectUri.get_sql_alchemy_model()


class ApiKey(_InternalAuthResource):
    """A revocable backing row for an API-key credential.

    Only a SHA-256 ``key_hash`` and a non-secret ``prefix`` are stored; the raw
    key is returned once at create time and never persisted.
    """

    id: Annotated[
        UUID,
        ResourceyField(column=Column("id", Uuid, primary_key=True, default=uuid4, nullable=False)),
    ]
    key_hash: Annotated[
        str,
        ResourceyField(
            column=Column("key_hash", String(64), nullable=False, unique=True, index=True)
        ),
    ]
    prefix: Annotated[str, ResourceyField(column=Column("prefix", String(32), nullable=False))]
    creator_id: Annotated[
        UUID,
        ResourceyField(
            column=Column(
                "creator_id",
                Uuid,
                ForeignKey("users.id", ondelete="CASCADE"),
                nullable=False,
                index=True,
            )
        ),
    ]
    name: str | None = None
    enabled: bool = True
    system: bool = False
    expires_at: datetime | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


_ApiKeyModel = ApiKey.get_sql_alchemy_model()
