"""Alembic environment (generated by resourcey, issue #3).

Targets ``ResourceyBase.metadata`` and registers the configured resource
classes so autogeneration sees every table. Alembic drives a *synchronous*
engine; the sync URL is set on the config by ``build_alembic_config``.
"""
from __future__ import annotations

from alembic import context
from sqlalchemy import engine_from_config, pool

from resourcey.migrate.migrate_runner import register_resources_from_env
from resourcey.resource.sql import ResourceyBase

config = context.config

# Resolve RESOURCEY_RESOURCES (dotted class paths) -> register_resource, so the
# derived tables are in metadata before the autogenerate diff runs.
register_resources_from_env()

target_metadata = ResourceyBase.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
