"""Alembic environment (generated by resourcey).

Imports the app's ResourceManifest and materialises its tables so
autogeneration sees every table. Every entity in this app — the message-board
resources and the auth backing entities (IdP tokens, OAuth clients, API keys) —
is declared as a resource, so ``ResourceyBase.metadata`` alone is the
migration target: no hand-written ``AuthBase`` merge is needed.
"""
from __future__ import annotations

from alembic import context
from resourcey.config.config_framework import FrameworkConfig
from resourcey.config.config_runtime import get_config_as
from resourcey.resource.sql import ResourceyBase
from resourcey.util.import_paths import resolve_import_path
from sqlalchemy import engine_from_config, pool

config = context.config

# Import the manifest from config and materialise tables into metadata.
cfg = get_config_as(FrameworkConfig)
manifest = resolve_import_path(cfg.manifest)
manifest.materialize()

target_metadata = ResourceyBase.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
