"""Alembic environment (generated by resourcey).

Imports the app's ResourceManifest and materialises its tables so
autogeneration sees every table. The auth feature's hand-written ORM models
(``AuthBase``) live in a separate metadata, so both metadatas are merged into
the Alembic ``target_metadata`` (ResourceyBase first, then the auth tables
not already present) — the ``users`` / ``user_permissions`` tables are shared
between the two, and the resource-generated model is the superset.
"""
from __future__ import annotations

from alembic import context
from resourcey.auth.auth_models import AuthBase
from resourcey.config.config_framework import FrameworkConfig
from resourcey.config.config_runtime import get_config_as
from resourcey.resource.sql import ResourceyBase
from resourcey.util.import_paths import resolve_import_path
from sqlalchemy import MetaData, engine_from_config, pool

config = context.config

# Import the manifest from config and materialise tables into metadata.
cfg = get_config_as(FrameworkConfig)
manifest = resolve_import_path(cfg.manifest)
manifest.materialize()


def _merged_metadata() -> MetaData:
    """Merge ResourceyBase + AuthBase tables into one target metadata.

    ResourceyBase tables win on name collisions (they are supersets — e.g. the
    resource-generated ``users`` table adds ``creator_id`` to the auth
    ``User`` model's columns), so AuthBase tables already present are skipped.
    """
    combined = MetaData()
    for table in ResourceyBase.metadata.tables.values():
        table.to_metadata(combined)
    for name, table in AuthBase.metadata.tables.items():
        if name not in combined.tables:
            table.to_metadata(combined)
    return combined


target_metadata = _merged_metadata()


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
