"""file store init

Revision ID: 7c1f4a9d2b6e
Revises:
Create Date: 2026-09-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1f4a9d2b6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The framework's conventional FileBlob model (the SQL medium's bytes
    # table) is the schema of record; this revision is its autogenerated
    # draft (reviewed). Only needed when MEDIUM_CLASS selects SqlFileStore --
    # the default Local medium needs no database table at all.
    op.create_table('file_blobs',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('etag', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('file_blobs')
