"""Alembic migration generation and apply/rollback for resourcey (issue #3).

Wraps Alembic so a resourcey app can generate database revisions from its
resource models without running ``alembic init`` or hand-writing an
``alembic.ini``. The entry points are:

* :func:`generate` — autogenerate a *draft* revision from
  :data:`ResourceyBase.metadata` (the manifest materialises tables into it
  via ``env.py``).
* :func:`upgrade` / :func:`downgrade` — apply or roll back revisions.
* :func:`init` — materialise ``env.py`` + ``versions/`` + ``script.py.mako``
  in the migrations directory.

The generated revision is a **draft**: Alembic's autogeneration cannot detect
table/column *renames* (they look like drop+create), so review every revision
before applying it. Run ``alembic`` directly to escape this wrapper.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from alembic import command as alembic_command
from alembic.config import Config as AlembicConfig

from resourcey.config.config_framework import MigrationConfig
from resourcey.resource.errors import ResourceyConfigError

# ``env.py`` executed by Alembic inside the migrations directory. It imports the
# app's manifest (discovered via ``FrameworkConfig.manifest``) and materialises
# its tables into ``ResourceyBase.metadata`` before the autogenerate diff runs.
# Generated versions are pure Alembic ops — no resourcey imports leak into them.
ENV_PY_SOURCE = '''"""Alembic environment (generated by resourcey).

Imports the app's ResourceManifest and materialises its tables so
autogeneration sees every table. Alembic drives a *synchronous* engine; the
sync URL is set on the config by ``build_alembic_config``.
"""
from __future__ import annotations

from alembic import context
from sqlalchemy import engine_from_config, pool

from resourcey.config.config_runtime import get_config_as
from resourcey.config.config_framework import FrameworkConfig
from resourcey.util.import_paths import resolve_import_path
from resourcey.resource.sql import ResourceyBase

config = context.config

# Import the manifest from config and materialise tables into metadata.
cfg = get_config_as(FrameworkConfig)
if cfg.manifest:
    manifest = resolve_import_path(cfg.manifest)
    manifest.materialize()

target_metadata = ResourceyBase.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def build_alembic_config(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    migrations_dir: str | Path | None = None,
) -> AlembicConfig:
    """Build an in-memory Alembic :class:`Config` (no ``alembic.ini`` needed).

    Points ``script_location`` at the migrations directory and sets the async
    SQLAlchemy URL (Alembic uses a sync engine — async drivers such as
    ``asyncpg`` / ``aiosqlite`` are stripped to their sync counterpart by
    :func:`_sync_database_url`). ``env.py`` imports the manifest from
    ``FrameworkConfig.manifest``, so no resource list is carried on the config.
    """
    directory = (
        Path(migrations_dir)
        if migrations_dir is not None
        else Path(migration_config.migrations_dir)
    )
    directory.mkdir(parents=True, exist_ok=True)
    env_path = directory / "env.py"
    if not env_path.exists():
        env_path.write_text(ENV_PY_SOURCE, encoding="utf-8")
    versions = directory / "versions"
    versions.mkdir(exist_ok=True)
    # Alembic renders each revision from ``script.py.mako`` looked up *inside
    # the script directory* (it ignores the ``script.py.mako`` config option
    # for generation). Copy the bundled template in so a freshly-created
    # migrations directory can generate revisions without ``alembic init``.
    mako_path = directory / "script.py.mako"
    if not mako_path.exists():
        mako_path.write_text(_default_script_template_source(), encoding="utf-8")

    config = AlembicConfig()
    config.set_main_option("script_location", str(directory))
    config.set_main_option("sqlalchemy.url", _sync_database_url(database_url))
    return config


def _sync_database_url(url: str) -> str:
    """Convert an async SQLAlchemy URL to its sync counterpart for Alembic.

    Alembic drives a synchronous engine. ``postgresql+asyncpg`` ->
    ``postgresql+psycopg2``, ``sqlite+aiosqlite`` -> ``sqlite``. Unknown
    drivers are returned unchanged (the caller may have passed a sync URL).
    """
    if "+asyncpg" in url:
        return url.replace("+asyncpg", "+psycopg2")
    if "+aiosqlite" in url:
        return url.replace("+aiosqlite", "")
    return url


def _default_script_template() -> str:
    """Locate Alembic's bundled ``script.py.mako`` revision template path.

    Avoids requiring ``alembic init``: a freshly-created migrations directory
    reuses the template that ships inside the installed ``alembic`` package.
    """
    import alembic

    return str(Path(alembic.__file__).parent / "templates" / "generic" / "script.py.mako")


def _default_script_template_source() -> str:
    """Read the bundled ``script.py.mako`` so it can be copied into the dir."""
    return Path(_default_script_template()).read_text(encoding="utf-8")


def generate(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    message: str,
) -> str:
    """Autogenerate a draft Alembic revision and return its file path.

    The revision is a draft — review it (and the rename-as-drop-create caveat)
    before applying. ``database_url`` is the async URL from
    :class:`~resourcey.config.config_framework.DbConfig`.
    """
    config = build_alembic_config(migration_config, database_url=database_url)
    script = alembic_command.revision(config, message=message, autogenerate=True)
    path = _script_path(script)
    if path is None:
        raise ResourceyConfigError("Alembic did not produce a revision file path")
    return path


def upgrade(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    revision: str = "head",
) -> None:
    """Apply migrations up to ``revision`` (default ``head``)."""
    config = build_alembic_config(migration_config, database_url=database_url)
    alembic_command.upgrade(config, revision)


def downgrade(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    revision: str = "-1",
) -> None:
    """Roll back migrations to ``revision`` (default ``-1``, one step back)."""
    config = build_alembic_config(migration_config, database_url=database_url)
    alembic_command.downgrade(config, revision)


def init(
    migration_config: MigrationConfig,
    *,
    database_url: str,
) -> str:
    """Materialise ``env.py`` + ``versions/`` + ``script.py.mako`` and return the dir.

    Idempotent: existing files are not overwritten. Unlike ``alembic init``,
    no ``alembic.ini`` is created — :func:`build_alembic_config` builds the
    config in memory.
    """
    config = build_alembic_config(migration_config, database_url=database_url)
    return config.get_main_option("script_location") or ""


def _script_path(script: Any) -> str | None:
    """Extract the revision file path from Alembic's revision() return value.

    Alembic returns either a ``Script`` (has ``.path``), a list of scripts,
    or ``None`` (when no revision is produced). Normalise to a single path.
    """
    if script is None:
        return None
    if isinstance(script, list):
        if not script:
            return None
        script = script[0]
    return getattr(script, "path", None)
