"""Alembic migration generation and apply/rollback for resourcey (issue #3).

Wraps Alembic so a resourcey app can generate database revisions from its
resource models without running ``alembic init`` or hand-writing an
``alembic.ini``. The entry points are:

* :func:`generate` — autogenerate a *draft* revision from
  :data:`ResourceyBase.metadata` (call :meth:`BaseResource.get_sql_alchemy_model`
  first, or let :func:`import_resource_modules` do it).
* :func:`upgrade` / :func:`downgrade` — apply or roll back revisions.
* :func:`init` — materialise ``env.py`` + ``versions/`` + ``script.py.mako``
  in the migrations directory.

The generated revision is a **draft**: Alembic's autogeneration cannot detect
table/column *renames* (they look like drop+create), so review every revision
before applying it. Run ``alembic`` directly to escape this wrapper.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from alembic import command as alembic_command
from alembic.config import Config as AlembicConfig

from resourcey.config.config_framework import MigrationConfig
from resourcey.resource.errors import ResourceyConfigError

# ``env.py`` executed by Alembic inside the migrations directory. It targets
# ``ResourceyBase.metadata`` (the shared declarative metadata that every
# ``BaseResource.get_sql_alchemy_model()`` registers into) and calls
# ``import_resource_modules()`` so the resource classes named in config are
# imported and their tables materialised before the diff runs.
ENV_PY_SOURCE = '''"""Alembic environment (generated by resourcey, issue #3).

Targets ``ResourceyBase.metadata`` and imports the configured resource modules
so autogeneration sees every table. Alembic drives a *synchronous* engine; the
sync URL is set on the config by ``build_alembic_config``.
"""
from __future__ import annotations

from alembic import context
from sqlalchemy import engine_from_config, pool

from resourcey.migrate.migrate_runner import import_resource_modules
from resourcey.resource.base import ResourceyBase

config = context.config

# Import + materialise resource models so their tables are in metadata before
# the autogenerate diff runs. Reads RESOURCEY_RESOURCE_MODULES* env vars set
# by build_alembic_config().
import_resource_modules()

target_metadata = ResourceyBase.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def import_resource_modules() -> None:
    """Import modules named in ``RESOURCEY_RESOURCE_MODULES``(+``_*``).

    Reads the env directly so ``env.py`` (which has no access to a config
    instance) can populate the resource registry before Alembic diffs.
    Sequential indices (``RESOURCEY_RESOURCE_MODULES_0`` ...) are supported,
    mirroring the env parser's list convention. An unimportable module raises
    :class:`ResourceyConfigError` naming the offender.

    Each named module is expected to call
    :func:`resourcey.resource.registry.register_resource` for every resource it
    defines. ``register_resource`` eagerly builds the SQLAlchemy model, so the
    derived tables are in :data:`ResourceyBase.metadata` by the time this
    returns — autogeneration sees them all without a separate materialisation
    pass.
    """
    import importlib

    from resourcey.resource.base import BaseResource
    from resourcey.resource.registry import get_registered_resources, register_resource

    modules: list[str] = []
    if "RESOURCEY_RESOURCE_MODULES" in os.environ:
        raw = os.environ["RESOURCEY_RESOURCE_MODULES"].strip()
        if raw:
            modules.extend(m.strip() for m in raw.split(",") if m.strip())
    i = 0
    while True:
        key = f"RESOURCEY_RESOURCE_MODULES_{i}"
        if key not in os.environ:
            break
        modules.append(os.environ[key].strip())
        i += 1

    for name in modules:
        try:
            mod = importlib.import_module(name)
        except ImportError as exc:
            raise ResourceyConfigError(
                f"Could not import resource module {name!r} for migrations: {exc}"
            ) from exc
        # ``import_module`` returns the cached module without re-executing the
        # body on a second import, so module-level ``register_resource`` calls
        # won't re-fire. Re-register every ``BaseResource`` subclass defined in
        # the named module so the registry is current regardless of import
        # state. ``register_resource`` is idempotent, so freshly-imported
        # modules (whose body already called it) are unaffected.
        for attr_name in dir(mod):
            obj = getattr(mod, attr_name)
            if (
                isinstance(obj, type)
                and obj is not BaseResource
                and issubclass(obj, BaseResource)
                and obj.__module__ == name
            ):
                register_resource(obj)

    # ``register_resource`` materialises each class on registration, so the
    # registry is already populated. Touch the result so a static analyser
    # sees the import is used and so a future lazy-registration scheme would
    # still be exercised here.
    get_registered_resources()


def build_alembic_config(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    migrations_dir: str | Path | None = None,
    resource_modules: list[str] | None = None,
) -> AlembicConfig:
    """Build an in-memory Alembic :class:`Config` (no ``alembic.ini`` needed).

    Points ``script_location`` at the migrations directory, sets the async
    SQLAlchemy URL (Alembic uses a sync engine — async drivers such as
    ``asyncpg`` / ``aiosqlite`` are stripped to their sync counterpart by
    :func:`_sync_database_url`), and records the resource modules in the
    environment so ``env.py`` can re-read them without a config instance.
    ``resource_modules`` comes from
    :attr:`FrameworkConfig.resource_modules` (an app-level concern); when
    ``None`` the existing ``RESOURCEY_RESOURCE_MODULES`` env var is left
    untouched.
    """
    directory = (
        Path(migrations_dir)
        if migrations_dir is not None
        else Path(migration_config.migrations_dir)
    )
    directory.mkdir(parents=True, exist_ok=True)
    env_path = directory / "env.py"
    if not env_path.exists():
        env_path.write_text(ENV_PY_SOURCE, encoding="utf-8")
    versions = directory / "versions"
    versions.mkdir(exist_ok=True)
    # Alembic renders each revision from ``script.py.mako`` looked up *inside
    # the script directory* (it ignores the ``script.py.mako`` config option
    # for generation). Copy the bundled template in so a freshly-created
    # migrations directory can generate revisions without ``alembic init``.
    mako_path = directory / "script.py.mako"
    if not mako_path.exists():
        mako_path.write_text(_default_script_template_source(), encoding="utf-8")

    config = AlembicConfig()
    config.set_main_option("script_location", str(directory))
    config.set_main_option("sqlalchemy.url", _sync_database_url(database_url))
    # Carry the resource-module list into the environment so env.py's
    # import_resource_modules() picks it up without a config instance.
    if resource_modules is not None:
        os.environ["RESOURCEY_RESOURCE_MODULES"] = ",".join(resource_modules)
    return config


def _sync_database_url(url: str) -> str:
    """Convert an async SQLAlchemy URL to its sync counterpart for Alembic.

    Alembic drives a synchronous engine. ``postgresql+asyncpg`` ->
    ``postgresql+psycopg2``, ``sqlite+aiosqlite`` -> ``sqlite``. Unknown
    drivers are returned unchanged (the caller may have passed a sync URL).
    """
    if "+asyncpg" in url:
        return url.replace("+asyncpg", "+psycopg2")
    if "+aiosqlite" in url:
        return url.replace("+aiosqlite", "")
    return url


def _default_script_template() -> str:
    """Locate Alembic's bundled ``script.py.mako`` revision template path.

    Avoids requiring ``alembic init``: a freshly-created migrations directory
    reuses the template that ships inside the installed ``alembic`` package.
    """
    import alembic

    return str(Path(alembic.__file__).parent / "templates" / "generic" / "script.py.mako")


def _default_script_template_source() -> str:
    """Read the bundled ``script.py.mako`` so it can be copied into the dir."""
    return Path(_default_script_template()).read_text(encoding="utf-8")


def generate(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    message: str,
    resource_modules: list[str] | None = None,
) -> str:
    """Autogenerate a draft Alembic revision and return its file path.

    The revision is a draft — review it (and the rename-as-drop-create caveat)
    before applying. ``database_url`` is the async URL from
    :class:`~resourcey.config.config_framework.DbConfig`.
    ``resource_modules`` comes from
    :attr:`FrameworkConfig.resource_modules`.
    """
    config = build_alembic_config(
        migration_config, database_url=database_url, resource_modules=resource_modules
    )
    script = alembic_command.revision(config, message=message, autogenerate=True)
    path = _script_path(script)
    if path is None:
        raise ResourceyConfigError("Alembic did not produce a revision file path")
    return path


def upgrade(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    revision: str = "head",
    resource_modules: list[str] | None = None,
) -> None:
    """Apply migrations up to ``revision`` (default ``head``)."""
    config = build_alembic_config(
        migration_config, database_url=database_url, resource_modules=resource_modules
    )
    alembic_command.upgrade(config, revision)


def downgrade(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    revision: str = "-1",
    resource_modules: list[str] | None = None,
) -> None:
    """Roll back migrations to ``revision`` (default ``-1``, one step back)."""
    config = build_alembic_config(
        migration_config, database_url=database_url, resource_modules=resource_modules
    )
    alembic_command.downgrade(config, revision)


def init(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    resource_modules: list[str] | None = None,
) -> str:
    """Materialise ``env.py`` + ``versions/`` + ``script.py.mako`` and return the dir.

    Idempotent: existing files are not overwritten. Unlike ``alembic init``,
    no ``alembic.ini`` is created — :func:`build_alembic_config` builds the
    config in memory.
    """
    config = build_alembic_config(
        migration_config, database_url=database_url, resource_modules=resource_modules
    )
    return config.get_main_option("script_location") or ""


def _script_path(script: Any) -> str | None:
    """Extract the revision file path from Alembic's revision() return value.

    Alembic returns either a ``Script`` (has ``.path``), a list of scripts,
    or ``None`` (when no revision is produced). Normalise to a single path.
    """
    if script is None:
        return None
    if isinstance(script, list):
        if not script:
            return None
        script = script[0]
    return getattr(script, "path", None)
