"""Alembic migration generation and apply/rollback for resourcey (issue #3).

Wraps Alembic so a resourcey app can generate database revisions from its
resource models without running ``alembic init`` or hand-writing an
``alembic.ini``. The entry points are:

* :func:`generate` — autogenerate a *draft* revision from
  :data:`ResourceyBase.metadata` (call :meth:`BaseResource.get_sql_alchemy_model`
  first, or let :func:`register_resources` do it).
* :func:`upgrade` / :func:`downgrade` — apply or roll back revisions.
* :func:`init` — materialise ``env.py`` + ``versions/`` + ``script.py.mako``
  in the migrations directory.

The generated revision is a **draft**: Alembic's autogeneration cannot detect
table/column *renames* (they look like drop+create), so review every revision
before applying it. Run ``alembic`` directly to escape this wrapper.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from alembic import command as alembic_command
from alembic.config import Config as AlembicConfig

from resourcey.config.config_framework import MigrationConfig
from resourcey.resource.errors import ResourceyConfigError

# ``env.py`` executed by Alembic inside the migrations directory. It targets
# ``ResourceyBase.metadata`` (the shared declarative metadata that every
# ``BaseResource.get_sql_alchemy_model()`` registers into) and calls
# ``register_resources_from_env()`` so the resource classes named in config are
# imported, registered, and their tables materialised before the diff runs.
ENV_PY_SOURCE = '''"""Alembic environment (generated by resourcey, issue #3).

Targets ``ResourceyBase.metadata`` and registers the configured resource
classes so autogeneration sees every table. Alembic drives a *synchronous*
engine; the sync URL is set on the config by ``build_alembic_config``.
"""
from __future__ import annotations

from alembic import context
from sqlalchemy import engine_from_config, pool

from resourcey.migrate.migrate_runner import register_resources_from_env
from resourcey.resource.base import ResourceyBase

config = context.config

# Resolve RESOURCEY_RESOURCES (dotted class paths) -> register_resource, so the
# derived tables are in metadata before the autogenerate diff runs.
register_resources_from_env()

target_metadata = ResourceyBase.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def register_resources_from_env() -> None:
    """Register resource classes named in ``RESOURCEY_RESOURCES`` env vars.

    Reads the env directly so ``env.py`` (which has no access to a config
    instance) can populate the resource registry before Alembic diffs. The env
    representation is a JSON array (``RESOURCEY_RESOURCES``) or the sequential
    form (``RESOURCEY_RESOURCES_0`` / ``_1`` …) of dotted import paths, the
    same convention as :attr:`FrameworkConfig.resources`. Each path resolves to
    a class via :func:`resolve_import_path`; the class is then handed to
    :func:`register_resource`, which eagerly builds its SQLAlchemy model so
    the table is in :data:`ResourceyBase.metadata` by the time this returns.
    An unimportable path raises :class:`ResourceyConfigError`.
    """
    from resourcey.resource.base import BaseResource
    from resourcey.resource.registry import get_registered_resources, register_resource
    from resourcey.util.import_paths import resolve_import_path

    paths = _read_resources_env()
    for fqn in paths:
        try:
            cls = resolve_import_path(fqn)
        except (ImportError, AttributeError, ValueError) as exc:
            raise ResourceyConfigError(
                f"Could not resolve resource path {fqn!r} for migrations: {exc}"
            ) from exc
        if not (isinstance(cls, type) and issubclass(cls, BaseResource)):
            raise ResourceyConfigError(
                f"Resource path {fqn!r} does not resolve to a BaseResource subclass"
            )
        register_resource(cls)
    # ``register_resource`` materialises each class on registration, so the
    # registry is already populated. Touch the result so a static analyser
    # sees the import is used and so a future lazy-registration scheme would
    # still be exercised here.
    get_registered_resources()


def _read_resources_env() -> list[str]:
    """Collect dotted import paths from ``RESOURCEY_RESOURCES``(+``_*``).

    The JSON-array form (``RESOURCEY_RESOURCES='["a.B","c.D"]'``) and the
    sequential form (``RESOURCEY_RESOURCES_0=a.B``) are both supported.
    Returns ``[]`` when nothing is set.
    """
    import json

    paths: list[str] = []
    if "RESOURCEY_RESOURCES" in os.environ:
        raw = os.environ["RESOURCEY_RESOURCES"].strip()
        if raw:
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError:
                # Not JSON — treat as a comma-separated list for convenience.
                paths.extend(p.strip() for p in raw.split(",") if p.strip())
            else:
                if isinstance(parsed, list):
                    paths.extend(str(p).strip() for p in parsed if str(p).strip())
                else:
                    raise ResourceyConfigError(
                        f"RESOURCEY_RESOURCES must be a JSON array, got {raw!r}"
                    )
    i = 0
    while True:
        key = f"RESOURCEY_RESOURCES_{i}"
        if key not in os.environ:
            break
        paths.append(os.environ[key].strip())
        i += 1
    return paths


def build_alembic_config(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    migrations_dir: str | Path | None = None,
) -> AlembicConfig:
    """Build an in-memory Alembic :class:`Config` (no ``alembic.ini`` needed).

    Points ``script_location`` at the migrations directory and sets the async
    SQLAlchemy URL (Alembic uses a sync engine — async drivers such as
    ``asyncpg`` / ``aiosqlite`` are stripped to their sync counterpart by
    :func:`_sync_database_url`). ``env.py`` reads ``RESOURCEY_RESOURCES`` from
    the environment directly, so no resource list is carried on the config.
    """
    directory = (
        Path(migrations_dir)
        if migrations_dir is not None
        else Path(migration_config.migrations_dir)
    )
    directory.mkdir(parents=True, exist_ok=True)
    env_path = directory / "env.py"
    if not env_path.exists():
        env_path.write_text(ENV_PY_SOURCE, encoding="utf-8")
    versions = directory / "versions"
    versions.mkdir(exist_ok=True)
    # Alembic renders each revision from ``script.py.mako`` looked up *inside
    # the script directory* (it ignores the ``script.py.mako`` config option
    # for generation). Copy the bundled template in so a freshly-created
    # migrations directory can generate revisions without ``alembic init``.
    mako_path = directory / "script.py.mako"
    if not mako_path.exists():
        mako_path.write_text(_default_script_template_source(), encoding="utf-8")

    config = AlembicConfig()
    config.set_main_option("script_location", str(directory))
    config.set_main_option("sqlalchemy.url", _sync_database_url(database_url))
    return config


def _sync_database_url(url: str) -> str:
    """Convert an async SQLAlchemy URL to its sync counterpart for Alembic.

    Alembic drives a synchronous engine. ``postgresql+asyncpg`` ->
    ``postgresql+psycopg2``, ``sqlite+aiosqlite`` -> ``sqlite``. Unknown
    drivers are returned unchanged (the caller may have passed a sync URL).
    """
    if "+asyncpg" in url:
        return url.replace("+asyncpg", "+psycopg2")
    if "+aiosqlite" in url:
        return url.replace("+aiosqlite", "")
    return url


def _default_script_template() -> str:
    """Locate Alembic's bundled ``script.py.mako`` revision template path.

    Avoids requiring ``alembic init``: a freshly-created migrations directory
    reuses the template that ships inside the installed ``alembic`` package.
    """
    import alembic

    return str(Path(alembic.__file__).parent / "templates" / "generic" / "script.py.mako")


def _default_script_template_source() -> str:
    """Read the bundled ``script.py.mako`` so it can be copied into the dir."""
    return Path(_default_script_template()).read_text(encoding="utf-8")


def generate(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    message: str,
) -> str:
    """Autogenerate a draft Alembic revision and return its file path.

    The revision is a draft — review it (and the rename-as-drop-create caveat)
    before applying. ``database_url`` is the async URL from
    :class:`~resourcey.config.config_framework.DbConfig`.
    """
    config = build_alembic_config(migration_config, database_url=database_url)
    script = alembic_command.revision(config, message=message, autogenerate=True)
    path = _script_path(script)
    if path is None:
        raise ResourceyConfigError("Alembic did not produce a revision file path")
    return path


def upgrade(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    revision: str = "head",
) -> None:
    """Apply migrations up to ``revision`` (default ``head``)."""
    config = build_alembic_config(migration_config, database_url=database_url)
    alembic_command.upgrade(config, revision)


def downgrade(
    migration_config: MigrationConfig,
    *,
    database_url: str,
    revision: str = "-1",
) -> None:
    """Roll back migrations to ``revision`` (default ``-1``, one step back)."""
    config = build_alembic_config(migration_config, database_url=database_url)
    alembic_command.downgrade(config, revision)


def init(
    migration_config: MigrationConfig,
    *,
    database_url: str,
) -> str:
    """Materialise ``env.py`` + ``versions/`` + ``script.py.mako`` and return the dir.

    Idempotent: existing files are not overwritten. Unlike ``alembic init``,
    no ``alembic.ini`` is created — :func:`build_alembic_config` builds the
    config in memory.
    """
    config = build_alembic_config(migration_config, database_url=database_url)
    return config.get_main_option("script_location") or ""


def _script_path(script: Any) -> str | None:
    """Extract the revision file path from Alembic's revision() return value.

    Alembic returns either a ``Script`` (has ``.path``), a list of scripts,
    or ``None`` (when no revision is produced). Normalise to a single path.
    """
    if script is None:
        return None
    if isinstance(script, list):
        if not script:
            return None
        script = script[0]
    return getattr(script, "path", None)
