"""jobs init

Revision ID: dcd21e3e5d49
Revises: 
Create Date: 2026-10-07 15:09:12.086578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd21e3e5d49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_details_kind', sa.String(length=128), nullable=False),
    sa.Column('job_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'ERROR', 'CANCELLED', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('max_seconds_for_run', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_claimed_by'), 'jobs', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_jobs_creator_id'), 'jobs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_details_kind'), 'jobs', ['job_details_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_details_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_creator_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_claimed_by'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
