"""Per-field behavioural metadata for resources.

A ``ResourceyConfig`` is attached to a resource field via
``Annotated[type, ResourceyConfig(...)]`` and retrieved from
``FieldInfo.metadata`` -- the canonical Pydantic v2 mechanism for custom field
metadata (not ``json_schema_extra``, which is for JSON-schema customization
and is not a general metadata bag).

It is the single place where per-field behavioural flags live. The five
fields here are the initial set; additional flags (e.g. ``indexed``,
``unique``, permissions) are expected to be added later as the framework
grows, so the model is intentionally extensible.

``frozen=True`` prevents accidental mutation of a shared config instance, and
``arbitrary_types_allowed=True`` lets it hold a SQLAlchemy ``Column``.
"""

from __future__ import annotations

from typing import Any, cast

from pydantic import BaseModel, ConfigDict
from pydantic_core import CoreSchema
from sqlalchemy import Column


class ResourceyConfig(BaseModel):
    """Per-field behavioural flags for a resource.

    Attributes:
        creatable: Whether the field may be supplied on a create request.
        updatable: Whether the field may be supplied on an update request.
        readable: Whether the field is exposed on a read response.
        sortable: Whether the field may be used in ``sort=field``. Defaults
            to ``True`` for ordinary fields and ``False`` for ``SecretStr``
            fields (see :meth:`BaseResource.get_config_for_field`) so secret
            values cannot have their relative ordering inferred via sort.
            (Filtering is gated per-resource by a declared search filter
            class -- see :meth:`BaseResource.get_search_filter` -- not by a
            per-field flag.)
        column: Explicit SQLAlchemy column override. When ``None`` the column
            is generated by ``BaseResource.get_column_for_field``.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True, frozen=True)

    creatable: bool = True
    updatable: bool = True
    readable: bool = True
    sortable: bool = True
    column: Column[Any] | None = None

    @classmethod
    def __get_pydantic_core_schema__(cls, source: Any, handler: Any) -> CoreSchema:
        # ResourceyConfig is behavioural metadata attached via ``Annotated``;
        # it is not a schema source for the annotated field. Because it is a
        # BaseModel subclass, Pydantic asks it for a core schema when it
        # appears as Annotated metadata. Delegate to the inner handler so the
        # field keeps its real type's schema and the deprecated
        # ``BaseModel.__get_pydantic_core_schema__`` is not invoked.
        return cast(CoreSchema, handler(source))
