"""Alembic migration generation from the ``v2`` in-memory models (issue #78).

Because every :class:`~resourcey.v2.sql.resource.SqlResource` either adopts the
model recorded in its DTO's metadata or generates one, constructing the
resources and the manifest materialises *all* models in memory. By the time
migrations run, the full current schema exists in a SQLAlchemy declarative
base's metadata.

:func:`generate_migration` therefore takes a target declarative **base**,
enumerates all its tables (``base.metadata.tables``) and drives Alembic
autogeneration over that metadata. The base may be a class or a
``package.subpackage:Base`` string.

Alembic diffs the in-memory models against the *live* database, so it needs a
connection too — but a resource's session factory hides its URL and an adopted
model may carry its own engine, so there is no reliable single URL on the
resources. ``database_url`` is therefore an explicit argument. An async-driver
URL (``postgresql+asyncpg``, ``sqlite+aiosqlite``) is normalised to its sync
counterpart by a small local helper (Alembic drives a sync engine).

Generated revisions are **drafts**: Alembic cannot detect renames (they look
like drop + create), so every revision is review-required before applying.

The ``__main__`` block **generates only** — it never applies a revision (that
would mutate a real database from a ``-m`` invocation)::

    python -m resourcey.v2.sql.migration myapp.models:Base -m "initial"

This module is part of ``v2/``: it imports no ``resourcey`` code outside ``v2/``.
"""

from __future__ import annotations

import argparse
import importlib
import os
import sys
from pathlib import Path
from typing import Any

from alembic import command as alembic_command
from alembic.config import Config as AlembicConfig
from sqlalchemy.orm import DeclarativeBase

# Alembic's env.py inside the migrations directory. The target metadata is taken
# from the config: ``generate_migration`` sets it in-process via
# ``config.attributes``, and also sets the ``resourcey.base`` main option
# (``package.module:Base``) so a plain ``alembic`` run can resolve it. Metadata is
# allowed to be ``None`` because applying (``upgrade`` / ``downgrade``) does not
# need it — only autogeneration does.
ENV_PY_SOURCE = '''"""Alembic environment (generated by resourcey.v2.sql)."""
from __future__ import annotations

import importlib

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config


def _resolve_target_metadata() -> object:
    """The metadata to diff against: set in-process, else from the base path.

    Returns ``None`` when no base path is available or it cannot be imported
    (e.g. a locally-defined base); applying a revision does not need metadata.
    """
    target = config.attributes.get("target_metadata")
    if target is not None:
        return target
    base_path = config.get_main_option("resourcey.base")
    if not base_path:
        return None
    module_name, _, attr_name = base_path.partition(":")
    try:
        base = getattr(importlib.import_module(module_name), attr_name)
    except (ImportError, AttributeError):
        return None
    return base.metadata


target_metadata = _resolve_target_metadata()


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (connect and apply)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def generate_migration(
    base: type[DeclarativeBase] | str,
    *,
    database_url: str,
    message: str,
    migrations_dir: str | Path = "migrations",
) -> str:
    """Autogenerate a draft Alembic revision from ``base``'s models; return its path.

    Args:
        base: The declarative base whose metadata holds the current models, or a
            ``package.subpackage:Base`` string naming it.
        database_url: The (async or sync) URL of the database to diff against.
        message: The revision message.
        migrations_dir: Where the Alembic script directory lives (created on demand).
    """
    resolved_base = resolve_base(base)
    config = _build_alembic_config(resolved_base, database_url, migrations_dir)
    script = alembic_command.revision(config, message=message, autogenerate=True)
    path = _script_path(script)
    if path is None:
        raise RuntimeError("Alembic did not produce a revision file path")
    return path


def resolve_base(base: type[DeclarativeBase] | str) -> type[DeclarativeBase]:
    """Resolve ``base`` (a class or ``package.subpackage:Base`` string) to a class."""
    if not isinstance(base, str):
        return base
    module_name, _, attr_name = base.partition(":")
    if not module_name or not attr_name:
        raise ValueError(f"Base path {base!r} must be of the form 'package.module:Base'")
    module = importlib.import_module(module_name)
    resolved: Any = getattr(module, attr_name)
    if not (isinstance(resolved, type) and issubclass(resolved, DeclarativeBase)):
        raise TypeError(f"{base!r} does not resolve to a declarative base subclass")
    return resolved


def _build_alembic_config(
    base: type[DeclarativeBase],
    database_url: str,
    migrations_dir: str | Path,
) -> AlembicConfig:
    """Build an in-memory Alembic config pointing at ``migrations_dir``."""
    directory = Path(migrations_dir)
    directory.mkdir(parents=True, exist_ok=True)
    env_path = directory / "env.py"
    if not env_path.exists():
        env_path.write_text(ENV_PY_SOURCE, encoding="utf-8")
    (directory / "versions").mkdir(exist_ok=True)
    # Alembic renders each revision from ``script.py.mako`` *inside* the script
    # directory, so copy the bundled template in to avoid ``alembic init``.
    mako_path = directory / "script.py.mako"
    if not mako_path.exists():
        mako_path.write_text(_default_script_template_source(), encoding="utf-8")

    config = AlembicConfig()
    config.set_main_option("script_location", str(directory))
    config.set_main_option("sqlalchemy.url", sync_database_url(database_url))
    config.attributes["target_metadata"] = base.metadata
    # Also record the base's dotted path so the generated env.py can resolve the
    # metadata on a later plain ``alembic`` run (see ``_base_path``).
    if (base_path := _base_path(base)) is not None:
        config.set_main_option("resourcey.base", base_path)
    return config


def _base_path(base: type[DeclarativeBase]) -> str | None:
    """The ``module:QualName`` path of ``base``, or ``None`` for a local class.

    A locally-defined base (e.g. in a test or a script) has no importable
    qualified path, so nothing is recorded and a plain ``alembic`` run falls
    back to no target metadata.
    """
    module = getattr(base, "__module__", None)
    qualname = getattr(base, "__qualname__", None)
    if not module or not qualname or "<locals>" in qualname:
        return None
    return f"{module}:{qualname}"


def sync_database_url(url: str) -> str:
    """Convert an async SQLAlchemy URL to its sync counterpart for Alembic.

    Alembic drives a synchronous engine. ``postgresql+asyncpg`` ->
    ``postgresql+psycopg2``, ``sqlite+aiosqlite`` -> ``sqlite``. Unknown drivers
    are returned unchanged (the caller may have passed a sync URL).
    """
    if "+asyncpg" in url:
        return url.replace("+asyncpg", "+psycopg2")
    if "+aiosqlite" in url:
        return url.replace("+aiosqlite", "")
    return url


def _default_script_template_source() -> str:
    """Read Alembic's bundled ``script.py.mako`` so it can be copied into the dir."""
    import alembic

    template = Path(alembic.__file__).parent / "templates" / "generic" / "script.py.mako"
    return template.read_text(encoding="utf-8")


def _script_path(script: Any) -> str | None:
    """Extract the revision file path from Alembic's revision() return value."""
    if script is None:
        return None
    if isinstance(script, list):
        if not script:
            return None
        script = script[0]
    return getattr(script, "path", None)


def main(argv: list[str] | None = None) -> int:
    """Generate (never apply) a revision from a base path and a database URL.

    ``python -m resourcey.v2.sql.migration myapp.models:Base -m "initial"``
    """
    parser = argparse.ArgumentParser(
        prog="python -m resourcey.v2.sql.migration",
        description="Autogenerate a draft Alembic revision from a declarative base.",
    )
    parser.add_argument("base", help="Target base as 'package.module:Base'.")
    parser.add_argument("-m", "--message", required=True, help="The revision message.")
    parser.add_argument(
        "--database-url",
        default=os.environ.get("RESOURCEY_DATABASE_URL"),
        help="Database URL (falls back to $RESOURCEY_DATABASE_URL).",
    )
    parser.add_argument(
        "--migrations-dir",
        default="migrations",
        help="The Alembic script directory (default: migrations).",
    )
    args = parser.parse_args(argv)
    if not args.database_url:
        parser.error("a database URL is required (--database-url or $RESOURCEY_DATABASE_URL)")
    path = generate_migration(
        args.base,
        database_url=args.database_url,
        message=args.message,
        migrations_dir=args.migrations_dir,
    )
    print(path)
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    sys.exit(main())
