"""Tests for the stored (DB-backed) ``ApiKey`` resource (issue #63).

The security contract under test is "visible on create, never afterwards":

* the key is generated by the framework — a client can neither supply one on
  create nor change one on update;
* the ``201`` create response carries it exactly once, and it is the value
  actually persisted (so a later phase can authenticate against the row);
* no other surface discloses it — read, search, and batch-read responses, and
  the query surface (``?sort=key`` / ``?key__eq=``) alike.

Exercised at the model layer, the service layer (a real in-memory SQLite
session, no mocks), and over HTTP through the generated routes.
"""

from __future__ import annotations

import re
import warnings
from collections.abc import AsyncIterator
from typing import Any

import pytest
import pytest_asyncio
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from pydantic.json_schema import PydanticJsonSchemaWarning
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.pool import StaticPool

from resourcey.auth2.auth2_api_key_resource import (
    API_KEY_FORMAT,
    API_KEY_RANDOM_BITS,
    KEY_FIELD,
    ApiKey,
    encode_base36,
    generate_api_key,
)
from resourcey.auth2.auth2_api_key_service import ApiKeyService
from resourcey.resource.routes import register_error_handlers, register_routes
from resourcey.resource.sql import ResourceyBase

# A key is the preset format filled with a fixed-width base-36 secret.
_KEY_PATTERN = re.compile(r"^rsk_[0-9a-z]{50}$")


@pytest.fixture
def resource() -> ApiKey:
    instance = ApiKey()
    instance.on_register()
    return instance


@pytest_asyncio.fixture
async def session_factory() -> AsyncIterator[async_sessionmaker[AsyncSession]]:
    """In-memory SQLite (StaticPool so every session sees the same database)."""
    ApiKey().on_register()
    engine = create_async_engine("sqlite+aiosqlite:///:memory:", poolclass=StaticPool)
    async with engine.begin() as conn:
        await conn.run_sync(ResourceyBase.metadata.create_all)
    yield async_sessionmaker(engine, expire_on_commit=False)
    await engine.dispose()


@pytest_asyncio.fixture
async def session(
    session_factory: async_sessionmaker[AsyncSession],
) -> AsyncIterator[AsyncSession]:
    async with session_factory() as sess:
        yield sess


@pytest_asyncio.fixture
async def client(
    resource: ApiKey, session_factory: async_sessionmaker[AsyncSession]
) -> AsyncIterator[AsyncClient]:
    """An app serving the resource's generated routes."""
    resource._session_factory = session_factory
    app = FastAPI()
    register_routes(app, resource)
    register_error_handlers(app)
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


async def _create(client: AsyncClient, **body: Any) -> dict[str, Any]:
    response = await client.post("/api-keys", json=body)
    assert response.status_code == 201
    return dict(response.json())


def _openapi(app: FastAPI) -> dict[str, Any]:
    """Generate the OpenAPI schema, tolerating the framework's ``MISSING``-default
    ``PydanticJsonSchemaWarning`` (the update model's optional fields default to
    the sentinel). Unrelated to the key visibility under test; the suppression
    mirrors ``test_resource_service._openapi``."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", PydanticJsonSchemaWarning)
        return dict(app.openapi())


class TestKeyGeneration:
    def test_key_matches_the_preset_format(self) -> None:
        assert _KEY_PATTERN.match(generate_api_key())

    def test_keys_are_unique(self) -> None:
        assert len({generate_api_key() for _ in range(100)}) == 100

    def test_length_is_fixed_regardless_of_the_secret(self) -> None:
        """Zero-padding keeps a small secret from yielding a shorter key."""
        lengths = {len(generate_api_key()) for _ in range(100)}
        assert lengths == {len(API_KEY_FORMAT.format(secret="x" * 50))}

    def test_custom_format_is_honoured(self) -> None:
        assert generate_api_key("tenant-{secret}").startswith("tenant-")

    def test_secret_carries_the_declared_entropy(self) -> None:
        """50 base-36 digits span at least the declared 256 bits."""
        assert 2**API_KEY_RANDOM_BITS <= 36**50

    @pytest.mark.parametrize(
        ("value", "width", "expected"),
        [(0, 3, "000"), (35, 1, "z"), (36, 3, "010"), (1, 0, "1")],
    )
    def test_encode_base36(self, value: int, width: int, expected: str) -> None:
        assert encode_base36(value, width) == expected


class TestGeneratedModels:
    def test_key_is_not_creatable(self, resource: ApiKey) -> None:
        assert KEY_FIELD not in resource.get_create_model().model_fields

    def test_key_is_not_updatable(self, resource: ApiKey) -> None:
        assert KEY_FIELD not in resource.get_update_model().model_fields

    def test_key_is_not_readable(self, resource: ApiKey) -> None:
        assert KEY_FIELD not in resource.get_read_model().model_fields

    def test_read_model_keeps_the_non_secret_fields(self, resource: ApiKey) -> None:
        assert set(resource.get_read_model().model_fields) == {
            "id",
            "name",
            "created_at",
            "updated_at",
        }

    def test_name_is_the_only_editable_field(self, resource: ApiKey) -> None:
        assert set(resource.get_update_model().model_fields) == {"name"}

    def test_key_is_not_sortable(self, resource: ApiKey) -> None:
        """``?sort=key`` would leak the relative order of stored keys."""
        assert KEY_FIELD not in resource.get_sortable_fields()

    def test_key_is_not_queryable(self, resource: ApiKey) -> None:
        """``?key__eq=`` would let a client confirm a guessed key."""
        assert KEY_FIELD not in resource.get_queryable_fields()

    def test_key_column_is_unique_and_indexed(self, resource: ApiKey) -> None:
        column = resource.get_orm_model().__table__.c[KEY_FIELD]
        assert column.unique is True
        assert column.index is True
        assert column.nullable is False


class TestServiceCreate:
    @pytest.mark.asyncio
    async def test_create_reveals_a_generated_key(
        self, resource: ApiKey, session: AsyncSession
    ) -> None:
        service = ApiKeyService(resource, session=session)
        created = await service.create(resource.get_create_model()(name="ci"))
        assert _KEY_PATTERN.match(created.key)
        assert created.name == "ci"

    @pytest.mark.asyncio
    async def test_revealed_key_is_the_stored_key(
        self, resource: ApiKey, session: AsyncSession
    ) -> None:
        """The reveal must be the persisted value, or it could never authenticate."""
        service = ApiKeyService(resource, session=session)
        created = await service.create(resource.get_create_model()(name="ci"))
        row = (await session.execute(select(resource.get_orm_model()))).scalars().one()
        assert row.key == created.key

    @pytest.mark.asyncio
    async def test_each_create_mints_a_distinct_key(
        self, resource: ApiKey, session: AsyncSession
    ) -> None:
        service = ApiKeyService(resource, session=session)
        first = await service.create(resource.get_create_model()(name="a"))
        second = await service.create(resource.get_create_model()(name="b"))
        assert first.key != second.key

    @pytest.mark.asyncio
    async def test_name_is_optional(self, resource: ApiKey, session: AsyncSession) -> None:
        service = ApiKeyService(resource, session=session)
        created = await service.create(resource.get_create_model()())
        assert created.name is None
        assert _KEY_PATTERN.match(created.key)

    @pytest.mark.asyncio
    async def test_a_key_on_the_payload_is_ignored(
        self, resource: ApiKey, session: AsyncSession
    ) -> None:
        """A caller reaching the service directly still cannot choose the key.

        Over HTTP the create model has no ``key`` field at all, so this guards
        the service-level escape hatch rather than the route.
        """
        service = ApiKeyService(resource, session=session)
        payload = resource.get_create_model()(name="ci")
        object.__setattr__(payload, KEY_FIELD, "attacker-chosen")
        created = await service.create(payload)
        assert created.key != "attacker-chosen"

    @pytest.mark.asyncio
    async def test_other_actions_do_not_expose_the_key(
        self, resource: ApiKey, session: AsyncSession
    ) -> None:
        service = ApiKeyService(resource, session=session)
        created = await service.create(resource.get_create_model()(name="ci"))
        fetched = await service.read(created.id)
        page = await service.search()
        assert not hasattr(fetched, KEY_FIELD)
        assert all(not hasattr(item, KEY_FIELD) for item in page.items)


class TestHttp:
    @pytest.mark.asyncio
    async def test_create_returns_the_key_once(self, client: AsyncClient) -> None:
        body = await _create(client, name="ci")
        assert _KEY_PATTERN.match(body[KEY_FIELD])

    @pytest.mark.asyncio
    async def test_read_omits_the_key(self, client: AsyncClient) -> None:
        created = await _create(client, name="ci")
        response = await client.get(f"/api-keys/{created['id']}")
        assert response.status_code == 200
        assert KEY_FIELD not in response.json()

    @pytest.mark.asyncio
    async def test_search_omits_the_key(self, client: AsyncClient) -> None:
        await _create(client, name="ci")
        items = (await client.get("/api-keys")).json()["items"]
        assert items and all(KEY_FIELD not in item for item in items)

    @pytest.mark.asyncio
    async def test_batch_read_omits_the_key(self, client: AsyncClient) -> None:
        created = await _create(client, name="ci")
        items = (await client.get(f"/api-keys/batch-read?id={created['id']}")).json()
        assert items and all(KEY_FIELD not in item for item in items)

    @pytest.mark.asyncio
    async def test_a_supplied_key_is_ignored_on_create(self, client: AsyncClient) -> None:
        body = await _create(client, name="ci", key="attacker-chosen")
        assert body[KEY_FIELD] != "attacker-chosen"

    @pytest.mark.asyncio
    async def test_update_cannot_change_the_key(self, client: AsyncClient) -> None:
        created = await _create(client, name="ci")
        response = await client.patch(
            f"/api-keys/{created['id']}", json={"name": "renamed", "key": "attacker-chosen"}
        )
        assert response.status_code == 200
        assert response.json()["name"] == "renamed"
        assert KEY_FIELD not in response.json()

    @pytest.mark.asyncio
    async def test_update_leaves_the_stored_key_untouched(
        self,
        client: AsyncClient,
        resource: ApiKey,
        session_factory: async_sessionmaker[AsyncSession],
    ) -> None:
        created = await _create(client, name="ci")
        await client.patch(
            f"/api-keys/{created['id']}", json={"name": "renamed", "key": "attacker-chosen"}
        )
        async with session_factory() as sess:
            row = (await sess.execute(select(resource.get_orm_model()))).scalars().one()
        assert row.key == created[KEY_FIELD]

    @pytest.mark.asyncio
    async def test_sorting_by_key_is_rejected(self, client: AsyncClient) -> None:
        assert (await client.get("/api-keys?sort=key")).status_code == 422

    @pytest.mark.asyncio
    async def test_filtering_by_key_is_rejected(self, client: AsyncClient) -> None:
        response = await client.get("/api-keys?key__eq=rsk_whatever")
        assert response.status_code == 400
        assert response.json()["error"]["code"] == "invalid_input"

    @pytest.mark.asyncio
    async def test_key_is_absent_from_the_openapi_schemas(
        self, resource: ApiKey, session_factory: async_sessionmaker[AsyncSession]
    ) -> None:
        """Only the create response documents the key."""
        resource._session_factory = session_factory
        app = FastAPI()
        register_routes(app, resource)
        schemas = _openapi(app)["components"]["schemas"]
        assert KEY_FIELD not in schemas["ApiKeyCreate"]["properties"]
        assert KEY_FIELD not in schemas["ApiKeyUpdate"]["properties"]
        assert KEY_FIELD not in schemas["ApiKeyRead"]["properties"]

    @pytest.mark.asyncio
    async def test_a_revoked_key_is_gone(self, client: AsyncClient) -> None:
        created = await _create(client, name="ci")
        assert (await client.delete(f"/api-keys/{created['id']}")).status_code == 204
        assert (await client.get(f"/api-keys/{created['id']}")).status_code == 404
